# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurantdb',
            fields=[
                ('restaurant_id', models.CharField(max_length=225, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=225)),
                ('geocode', models.CharField(max_length=225)),
                ('address', models.CharField(blank=True, max_length=225, null=True)),
                ('image_url', models.CharField(blank=True, max_length=525, null=True)),
                ('visted', models.IntegerField(default=0)),
                ('google_rating', models.CharField(blank=True, max_length=225, null=True)),
            ],
        ),
    ]
