# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 19:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantReviews',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('reviews', models.CharField(max_length=225)),
                ('google_rating', models.CharField(blank=True, max_length=225, null=True)),
                ('registered_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='restaurant_api.Restaurantdb')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewsComments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('comments', models.CharField(max_length=255)),
                ('registered_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('reviews', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='restaurant_api.RestaurantReviews')),
            ],
        ),
    ]
