# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 11:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant_api', '0005_auto_20171013_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitedRes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('visted', models.IntegerField(blank=True, default=0, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('registered_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visited', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visited', to='restaurant_api.Restaurantdb')),
            ],
        ),
        migrations.AddField(
            model_name='restaurantreviews',
            name='visted',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
