# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 12:28
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message=b"Phone number     must be entered in the format: '+999999999'. Up to 12 digits allowed.", regex=b'^\\+?1?\\d{9,12}$')])),
                ('company_name', models.CharField(max_length=100)),
                ('profile_pic', models.ImageField(default=b'user.png', upload_to=b'')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
